export const foundations = [
    {
        "id": 1,
        "name": "Special Touch Animal Rescue",
        "lastName": "apellido",
        "email": "STARRadopt@aol.com",
        "role": "fundation",
        "active": true,
        "verification": false,
        "donaciones": 0,
        "address": null,
        "phone": "111111",
        "document": null,
        "countryId": "ARG",
        "cityId": 353
    },
    {
        "id": 2,
        "name": "Montgomery City Animal Shelter/Project Precious Paws",
        "lastName": "apellido",
        "email": "projectpreciouspaws@hotmail.com",
        "role": "fundation",
        "active": true,
        "verification": false,
        "donaciones": 0,
        "address": "915 Benton Street",
        "phone": "111111",
        "document": null,
        "countryId": "ARG",
        "cityId": 805
    },
    {
        "id": 3,
        "name": "Arizona Shih Tzu and Small Breed Rescue",
        "lastName": "apellido",
        "email": "ASTSBR@Gmail.com",
        "role": "fundation",
        "active": true,
        "verification": false,
        "donaciones": 0,
        "address": null,
        "phone": "111111",
        "document": null,
        "countryId": "CHL",
        "cityId": 525
    },
    {
        "id": 4,
        "name": "Kitten Care Group MN",
        "lastName": "apellido",
        "email": "kittencaregroupmn@gmail.com",
        "role": "fundation",
        "active": true,
        "verification": false,
        "donaciones": 0,
        "address": null,
        "phone": "111111",
        "document": null,
        "countryId": "CHL",
        "cityId": 654
    },
    {
        "id": 5,
        "name": "Pittsburgh Rat Lovers Club",
        "lastName": "apellido",
        "email": "kcyann@aol.com",
        "role": "fundation",
        "active": true,
        "verification": false,
        "donaciones": 0,
        "address": null,
        "phone": "111111",
        "document": null,
        "countryId": "COL",
        "cityId": 775
    },
    {
        "id": 6,
        "name": "Second Chance Rescue",
        "lastName": "apellido",
        "email": "secchancerescue@aol.com",
        "role": "fundation",
        "active": true,
        "verification": false,
        "donaciones": 0,
        "address": null,
        "phone": "111111",
        "document": null,
        "countryId": "COL",
        "cityId": 823
    },
    {
        "id": 7,
        "name": "Rose City Fox Terrier Rescue, Inc.",
        "lastName": "apellido",
        "email": "info@rosecityfoxterrierrescue.com",
        "role": "fundation",
        "active": true,
        "verification": false,
        "donaciones": 0,
        "address": null,
        "phone": "111111",
        "document": null,
        "countryId": "ECU",
        "cityId": 1734
    },
    {
        "id": 8,
        "name": "Tuff Tails Animal Rescue",
        "lastName": "apellido",
        "email": "info@tufftails.org",
        "role": "fundation",
        "active": true,
        "verification": false,
        "donaciones": 0,
        "address": "P.O. Box 117",
        "phone": "111111",
        "document": null,
        "countryId": "ECU",
        "cityId": 1783
    },
    {
        "id": 9,
        "name": "South Utah Valley Animal Shelter",
        "lastName": "apellido",
        "email": "doglicensedivision@gmail.com",
        "role": "fundation",
        "active": true,
        "verification": false,
        "donaciones": 0,
        "address": null,
        "phone": "111111",
        "document": null,
        "countryId": "PER",
        "cityId": 1836
    },
    {
        "id": 10,
        "name": "Second Chance Sheltie Rescue",
        "lastName": "apellido",
        "email": "sheltierescue@sheltie4me.com",
        "role": "fundation",
        "active": true,
        "verification": false,
        "donaciones": 0,
        "address": "P. O. Box 1791",
        "phone": "111111",
        "document": null,
        "countryId": "PER",
        "cityId": 1859
    }
]